version: '3.6'
services:
  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: testdb # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
 
volumes: # add volume to persist data.
  my-db:
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   user: root
  #   ports:
  #     - 1433:1433
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=aqui_123
  #   volumes:
  #     - ./data:/var/opt/mssql/data
  #   extra_hosts:
  #   - "host.docker.internal:host-gateway"
#  /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P aqui_123
# /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U SA -P aqui_123
# https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&preserve-view=true&pivots=cs1-bash
# https://go.dev/doc/tutorial/database-access